import React from 'react';
import EditNoteIcon from '@mui/icons-material/EditNote';
import CloudUploadIcon from '@mui/icons-material/CloudUpload';
import ContentPasteGoIcon from '@mui/icons-material/ContentPasteGo';
import PrintIcon from '@mui/icons-material/Print';
import PendingActionsIcon from '@mui/icons-material/PendingActions';
import UpgradeIcon from '@mui/icons-material/Upgrade';
import FileCopyIcon from '@mui/icons-material/FileCopy';
import DriveFileMoveIcon from '@mui/icons-material/DriveFileMove';
import HighlightOffIcon from '@mui/icons-material/HighlightOff';
import SmsIcon from '@mui/icons-material/Sms';
import LibraryAddIcon from '@mui/icons-material/LibraryAdd';
import ArchiveIcon from '@mui/icons-material/Archive';
/////
import InboxIcon from '@mui/icons-material/Inbox';
import TelegramIcon from '@mui/icons-material/Telegram';
import FolderOpenIcon from '@mui/icons-material/FolderOpen';
import SourceIcon from '@mui/icons-material/Source';
import NotificationsIcon from '@mui/icons-material/Notifications';
import EmailIcon from '@mui/icons-material/Email';
import ImportExportIcon from '@mui/icons-material/ImportExport';
import CloseIcon from "@mui/icons-material/Close";

export const EditIcons: React.FC = () => <EditNoteIcon/>;
export const UploadIcons: React.FC = () => <CloudUploadIcon/>;
export const PasteIcons: React.FC = () => <ContentPasteGoIcon/>;
export const PrintIcons: React.FC = () => <PrintIcon/>;
export const PendingIcons: React.FC = () => <PendingActionsIcon/>;
export const UpgradeIcons: React.FC = () => <UpgradeIcon/>;
export const FileCopyIcons: React.FC = () => <FileCopyIcon/>;
export const FilemoveIcons: React.FC = () => <DriveFileMoveIcon/>;
export const HighlightIcons: React.FC = () => <HighlightOffIcon/>;
export const SmsIcons: React.FC = () => <SmsIcon/>;
export const MakeIcons: React.FC = () => <LibraryAddIcon/>;
export const ArchiveIcons: React.FC = () => <ArchiveIcon/>;
/////
export const InboxIcons: React.FC = () => <InboxIcon/>;
export const ShareIcons: React.FC = () => <TelegramIcon/>;
export const FolderIcons: React.FC = () => <FolderOpenIcon/>;
export const SourceIcons: React.FC = () => <SourceIcon/>;
export const NotificationsIcons: React.FC = () => <NotificationsIcon/>;
export const EmailIcons: React.FC = () => <EmailIcon/>;
export const ImportExportIcons: React.FC = () => <ImportExportIcon/>;
export const CloseIcons: React.FC = () => <CloseIcon/>;